export function defaultRoomState() {
  return {
    targetISO: "",
    updatedAt: Date.now(),
    daily: null,
    playlist: [],

    // événements calendrier
    events: [],

    // 50 films immanquables Disney/Pixar et étrangers à voir ensemble
    movies: [
      // Films Disney/Pixar
      { title: "Le Roi Lion", done: false },
      { title: "Toy Story", done: false },
      { title: "La Belle et la Bête", done: false },
      { title: "Aladdin", done: false },
      { title: "La Petite Sirène", done: false },
      { title: "La Reine des Neiges", done: false },
      { title: "Vaiana", done: false },
      { title: "Coco", done: false },
      { title: "Vice Versa", done: false },
      { title: "Le Monde de Nemo", done: false },
      { title: "Les Indestructibles", done: false },
      { title: "Monstres & Cie", done: false },
      { title: "Cars", done: false },
      { title: "Ratatouille", done: false },
      { title: "WALL-E", done: false },
      { title: "Là-haut", done: false },
      { title: "Rebelle", done: false },
      { title: "Zootopie", done: false },
      { title: "Les Nouveaux Héros", done: false },
      { title: "Raiponce", done: false },
      { title: "La Princesse et la Grenouille", done: false },
      { title: "Les Mondes de Ralph", done: false },
      { title: "Winnie l'Ourson", done: false },
      { title: "Les Aventures de Winnie l'Ourson", done: false },
      { title: "Fantasia", done: false },
      // Films étrangers
      { title: "The Shawshank Redemption", done: false },
      { title: "The Godfather", done: false },
      { title: "Pulp Fiction", done: false },
      { title: "Inception", done: false },
      { title: "The Dark Knight", done: false },
      { title: "Forrest Gump", done: false },
      { title: "Fight Club", done: false },
      { title: "The Matrix", done: false },
      { title: "Titanic", done: false },
      { title: "Avatar", done: false },
      { title: "Star Wars : Épisode IV - Un nouvel espoir", done: false },
      { title: "Le Seigneur des Anneaux : La Communauté de l'Anneau", done: false },
      { title: "Harry Potter à l'école des sorciers", done: false },
      { title: "Jurassic Park", done: false },
      { title: "Schindler's List", done: false },
      { title: "Gladiator", done: false },
      { title: "Saving Private Ryan", done: false },
      { title: "Back to the Future", done: false },
      { title: "Raiders of the Lost Ark", done: false },
      { title: "E.T. the Extra-Terrestrial", done: false },
      { title: "Citizen Kane", done: false },
      { title: "Casablanca", done: false },
      { title: "Gone with the Wind", done: false },
      { title: "The Wizard of Oz", done: false },
      { title: "Psycho", done: false },
    ],

    // souvenirs partagés
    // memories: [],

    // notre to-do list
    todo: [
      { text: "Se faire un câlin de 5 minutes sans rien dire", done: false },
      { text: "Regarder un coucher de soleil ensemble", done: false },
      { text: "Faire une promenade main dans la main", done: false },
      { text: "Se cuisiner un repas à deux", done: false },
      { text: "Danser sur une chanson lente", done: false },
      { text: "Se raconter nos rêves pour l'avenir", done: false },
      { text: "Faire une bataille d'oreillers", done: false },
      { text: "Regarder des photos de nous deux", done: false },
      { text: "Se masser mutuellement", done: false },
      { text: "Faire une liste de nos souvenirs préférés", done: false },
      { text: "Se faire des compliments toute la journée", done: false },
      { text: "Aller se balader en forêt", done: false },
      { text: "Faire du shopping ensemble", done: false },
      { text: "Regarder un film sous la couette", done: false },
      { text: "Se préparer un petit-déjeuner au lit", done: false },
      { text: "Faire une soirée jeux de société", done: false },
      { text: "Aller au cinéma", done: false },
      { text: "Faire du sport ensemble", done: false },
      { text: "Visiter un musée", done: false },
      { text: "Faire une randonnée", done: false },
      { text: "Aller à la plage", done: false },
      { text: "Faire du vélo", done: false },
      { text: "Aller dans un parc d'attractions", done: false },
      { text: "Faire du camping", done: false },
      { text: "Aller à un concert", done: false },
      { text: "Faire une soirée karaoké", done: false },
      { text: "Aller dans un spa", done: false },
      { text: "Faire du yoga ensemble", done: false },
      { text: "Aller à une fête foraine", done: false },
      { text: "Faire une soirée pyjama", done: false },
      { text: "Aller dans un aquarium", done: false },
      { text: "Faire du patin à glace", done: false },
      { text: "Aller à un match de sport", done: false },
      { text: "Faire une soirée cinéma en plein air", done: false },
      { text: "Aller dans un zoo", done: false },
      { text: "Faire du kayak", done: false },
      { text: "Aller à une exposition", done: false },
      { text: "Faire une soirée jeux vidéo", done: false },
      { text: "Aller dans un parc national", done: false },
      { text: "Faire du surf", done: false },
      { text: "Aller à un festival", done: false },
      { text: "Faire une soirée peinture", done: false },
      { text: "Aller dans un vignoble", done: false },
      { text: "Faire du jardinage ensemble", done: false },
      { text: "Aller à une comédie musicale", done: false },
      { text: "Faire une soirée cuisine exotique", done: false },
      { text: "Aller dans un planétarium", done: false },
      { text: "Faire du ski", done: false },
      { text: "Aller à une dégustation de vins", done: false },
      { text: "Faire une soirée poésie", done: false },
    ],
    meet: {
      placeName: "",
      city: "",
      address: "",
      imageUrl: "",
      flight: {
        airline: "",
        flightNumber: "",
        departureAirport: "",
        departureTime: "",
        arrivalAirport: "",
        arrivalTime: "",
        bookingRef: "",
        notes: "",
      },
    },
  };
}

