export function defaultRoomState() {
  return {
    targetISO: "",
    updatedAt: Date.now(),
    daily: null,
    playlist: [],

    // événements calendrier
    events: [],

    // notre to-do list
    todo: [
      { text: "Se faire un câlin de 5 minutes sans rien dire", done: false },
      { text: "Regarder un coucher de soleil ensemble", done: false },
      { text: "Faire une promenade main dans la main", done: false },
      { text: "Se cuisiner un repas à deux", done: false },
      { text: "Danser sur une chanson lente", done: false },
      { text: "Se raconter nos rêves pour l'avenir", done: false },
      { text: "Faire une bataille d'oreillers", done: false },
      { text: "Regarder des photos de nous deux", done: false },
      { text: "Se masser mutuellement", done: false },
      { text: "Faire une liste de nos souvenirs préférés", done: false },
      { text: "Se faire des compliments toute la journée", done: false },
      { text: "Aller se balader en forêt", done: false },
      { text: "Faire du shopping ensemble", done: false },
      { text: "Regarder un film sous la couette", done: false },
      { text: "Se préparer un petit-déjeuner au lit", done: false },
      { text: "Faire une soirée jeux de société", done: false },
      { text: "Aller au cinéma", done: false },
      { text: "Faire du sport ensemble", done: false },
      { text: "Visiter un musée", done: false },
      { text: "Faire une randonnée", done: false },
      { text: "Aller à la plage", done: false },
      { text: "Faire du vélo", done: false },
      { text: "Aller dans un parc d'attractions", done: false },
      { text: "Faire du camping", done: false },
      { text: "Aller à un concert", done: false },
      { text: "Faire une soirée karaoké", done: false },
      { text: "Aller dans un spa", done: false },
      { text: "Faire du yoga ensemble", done: false },
      { text: "Aller à une fête foraine", done: false },
      { text: "Faire une soirée pyjama", done: false },
      { text: "Aller dans un aquarium", done: false },
      { text: "Faire du patin à glace", done: false },
      { text: "Aller à un match de sport", done: false },
      { text: "Faire une soirée cinéma en plein air", done: false },
      { text: "Aller dans un zoo", done: false },
      { text: "Faire du kayak", done: false },
      { text: "Aller à une exposition", done: false },
      { text: "Faire une soirée jeux vidéo", done: false },
      { text: "Aller dans un parc national", done: false },
      { text: "Faire du surf", done: false },
      { text: "Aller à un festival", done: false },
      { text: "Faire une soirée peinture", done: false },
      { text: "Aller dans un vignoble", done: false },
      { text: "Faire du jardinage ensemble", done: false },
      { text: "Aller à une comédie musicale", done: false },
      { text: "Faire une soirée cuisine exotique", done: false },
      { text: "Aller dans un planétarium", done: false },
      { text: "Faire du ski", done: false },
      { text: "Aller à une dégustation de vins", done: false },
      { text: "Faire une soirée poésie", done: false },
    ],
    meet: {
      placeName: "",
      city: "",
      address: "",
      imageUrl: "",
      flight: {
        airline: "",
        flightNumber: "",
        departureAirport: "",
        departureTime: "",
        arrivalAirport: "",
        arrivalTime: "",
        bookingRef: "",
        notes: "",
      },
    },
  };
}

